<?php

return [
    'Amazonas' => ['Leticia', 'Puerto Nariño', 'El Encanto'],
    'Antioquia' => ['Medellín', 'Bello', 'Envigado', 'Itagüí', 'Rionegro', 'Apartadó', 'Turbo', 'Caucasia', 'Chigorodó', 'Copacabana', 'Girardota', 'La Estrella', 'Sabaneta', 'Yarumal', 'Marinilla', 'Carmen de Viboral', 'Puerto Berrío', 'Támesis', 'Jardín', 'Jericó', 'Santa Fe de Antioquia', 'San Pedro de los Milagros'],
    'Arauca' => ['Arauca', 'Saravena', 'Tame', 'Fortul'],
    'Atlántico' => ['Barranquilla', 'Soledad', 'Malambo', 'Puerto Colombia', 'Sabanagrande', 'Santo Tomás', 'Galapa', 'Baranoa', 'Luruaco', 'Usiacurí'],
    'Bolívar' => ['Cartagena', 'Magangué', 'Turbaco', 'El Carmen de Bolívar', 'Mompós', 'Arjona', 'Mahates', 'San Pablo', 'María La Baja'],
    'Boyacá' => ['Tunja', 'Duitama', 'Sogamoso', 'Paipa', 'Chiquinquirá', 'Ramiriquí', 'Villa de Leyva', 'Monguí', 'Nobsa', 'Sutamarchán', 'Tuta', 'Samacá'],
    'Caldas' => ['Manizales', 'Villamaría', 'Chinchiná', 'La Dorada', 'Salamina', 'Aranzazu', 'Anserma', 'Riosucio', 'Supía'],
    'Caquetá' => ['Florencia', 'Cartagena del Chairá', 'San Vicente del Caguán', 'Puerto Rico', 'Belén de los Andaquíes'],
    'Casanare' => ['Yopal', 'Aguazul', 'Paz de Ariporo', 'Villanueva', 'Trinidad', 'Tauramena'],
    'Cauca' => ['Popayán', 'Santander de Quilichao', 'Puerto Tejada', 'Miranda', 'Corinto', 'Silvia', 'El Tambo', 'Patía (El Bordo)'],
    'Cesar' => ['Valledupar', 'Aguachica', 'Codazzi', 'Curumaní', 'San Alberto', 'San Diego', 'Bosconia'],
    'Chocó' => ['Quibdó', 'Istmina', 'Condoto', 'Nóvita', 'Bahía Solano', 'Nuquí'],
    'Córdoba' => ['Montería', 'Cereté', 'Lorica', 'Montelíbano', 'Tierralta', 'Sahagún', 'San Pelayo', 'Planeta Rica', 'Ciénaga de Oro'],
    'Cundinamarca' => ['Bogotá', 'Soacha', 'Girardot', 'Facatativá', 'Zipaquirá', 'Chía', 'Cajicá', 'Tabio', 'Tenjo', 'Cota', 'Funza', 'Mosquera', 'Madrid', 'La Calera', 'Sopó', 'Ubaté', 'Villeta', 'Fusagasugá', 'Sibaté', 'San Antonio del Tequendama'],
    'Guainía' => ['Inírida'],
    'Guaviare' => ['San José del Guaviare', 'Calamar', 'El Retorno'],
    'Huila' => ['Neiva', 'Pitalito', 'Garzón', 'La Plata', 'Campoalegre', 'San Agustín', 'Palermo', 'Rivera', 'Baraya'],
    'La Guajira' => ['Riohacha', 'Maicao', 'Uribia', 'San Juan del Cesar', 'Dibulla', 'Fonseca', 'Barrancas'],
    'Magdalena' => ['Santa Marta', 'Ciénaga', 'Fundación', 'El Banco', 'Plato', 'Aracataca', 'Pivijay', 'San Zenón'],
    'Meta' => ['Villavicencio', 'Acacías', 'Granada', 'Puerto López', 'San Martín', 'Restrepo', 'San Juan de Arama', 'La Macarena'],
    'Nariño' => ['Pasto', 'Tumaco', 'Ipiales', 'Túquerres', 'Samaniego', 'La Unión', 'Barbacoas', 'Cumbal', 'Guachucal'],
    'Norte de Santander' => ['Cúcuta', 'Ocaña', 'Pamplona', 'Los Patios', 'Villa del Rosario', 'Chinácota'],
    'Putumayo' => ['Mocoa', 'Puerto Asís', 'La Hormiga', 'Orito', 'Sibundoy', 'Valle del Guamuez'],
    'Quindío' => ['Armenia', 'Calarcá', 'Montenegro', 'Quimbaya', 'Salento', 'Buenavista', 'Filandia'],
    'Risaralda' => ['Pereira', 'Dosquebradas', 'Santa Rosa de Cabal', 'La Virginia', 'Marsella', 'Quinchía'],
    'San Andrés y Providencia' => ['San Andrés', 'Providencia'],
    'Santander' => ['Bucaramanga', 'Barrancabermeja', 'Floridablanca', 'Piedecuesta', 'San Gil', 'Socorro', 'Girón', 'Lebrija', 'Barbosa', 'Puente Nacional', 'Málaga', 'Vélez'],
    'Sucre' => ['Sincelejo', 'Corozal', 'San Marcos', 'Morroa', 'Sampués', 'Tolú', 'Toluviejo', 'Ovejas'],
    'Tolima' => ['Ibagué', 'Espinal', 'Líbano', 'Honda', 'Chaparral', 'Melgar', 'Mariquita', 'Falan', 'Saldaña', 'Rovira', 'Purificación'],
    'Valle del Cauca' => ['Cali', 'Buenaventura', 'Palmira', 'Tuluá', 'Cartago', 'Buga', 'Yumbo', 'Jamundí', 'Dagua', 'Roldanillo', 'Caicedonia', 'Sevilla', 'Zarzal', 'El Cerrito', 'Piedemonte'],
    'Vaupés' => ['Mitú', 'Carurú'],
    'Vichada' => ['Puerto Carreño', 'La Primavera', 'Santa Rosalía'],
];
